create table posts(
  id bigint generated by default as identity primary key,
  content text not null,
  user_id text not null default auth.jwt()->>'sub',
  created_at timestamptz default now()
);

alter table posts enable row level security;

create policy "User can view all posts"
on "public"."posts"
for select
to authenticated
using (true);

create policy "Users must insert their own posts"
on "public"."posts"
as permissive
for insert
to authenticated
with check (
((select auth.jwt()->>'sub') = (user_id)::text)
);
